export const villager_actions_intents = [
  {
    name: "mine",
    trainingPhrases: [
      "minerar",
      "escavar",
      "cavar",
      "cava aí",
      "vai minerar",
      "pegar minério",
      "buscar ferro",
      "achar diamante",
      "bora cavar",
      "fura o chão",
      "acha minério",
      "descer mina",
      "mine",
      "dig",
      "go mine",
      "start mining",
      "go dig some ores",
      "find ores",
      "get some stone",
      "get iron",
      "get diamonds",
    ],
    responses: [
      "Okay, I'll go mining.",
      "Heading to the caves now.",
      "Time to find some ores!",
    ],
  },
  {
    name: "build",
    trainingPhrases: [
      "construir",
      "montar casa",
      "erguer algo",
      "levantar parede",
      "fazer construção",
      "subir casa",
      "build",
      "make a house",
      "create a structure",
      "build something",
      "construct",
      "put up wall",
      "make base",
      "build base",
      "build tower",
    ],
    responses: [
      "Alright, I'll start building.",
      "Time to build something new.",
      "Let's get this structure up!",
    ],
  },
  {
    name: "hunt",
    trainingPhrases: [
      "caçar",
      "caça",
      "matar mobs",
      "matar monstro",
      "vai caçar",
      "buscar comida",
      "pegar carne",
      "ir pra caça",
      "hunt",
      "hunting",
      "go hunt",
      "kill mobs",
      "find food",
      "fight mobs",
      "get meat",
      "slay monsters",
    ],
    responses: [
      "Time to hunt for some food.",
      "I'll go take care of some mobs.",
      "Hunting it is!",
    ],
  },
  {
    name: "protect",
    trainingPhrases: [
      "proteger",
      "defender",
      "guardar",
      "ficar de guarda",
      "vigiar",
      "vigia vila",
      "segura as pontas",
      "protect",
      "defend",
      "guard",
      "keep safe",
      "stand guard",
      "watch village",
      "protect us",
      "protect villagers",
    ],
    responses: [
      "I'll stand guard and protect the village.",
      "Don't worry, I'll keep an eye out for danger.",
      "I will keep everyone safe.",
    ],
  },
  {
    name: "come_here",
    trainingPhrases: [
      "vem aqui",
      "chega mais",
      "cola aqui",
      "vem cá",
      "vem",
      "aqui ó",
      "aqui",
      "vem logo",
      "come",
      "come here",
      "to me",
      "come closer",
      "get here",
      "follow me",
      "this way",
      "over here",
    ],
    responses: ["On my way.", "Coming!", "Sure, where are you?"],
  },
  {
    name: "farm",
    trainingPhrases: [
      "plantar",
      "colher",
      "farmar",
      "cuidar da fazenda",
      "ir plantar",
      "recolher planta",
      "tratar da horta",
      "mexer na plantação",
      "farm",
      "harvest",
      "harvest crops",
      "grow plants",
      "plant seeds",
      "farm crops",
      "tend farm",
      "collect crops",
    ],
    responses: [
      "I'll tend the crops.",
      "Time to farm.",
      "Let's grow some food.",
    ],
  },
  {
    name: "gather",
    trainingPhrases: [
      "coletar",
      "catar",
      "buscar recursos",
      "pegar flores",
      "pegar madeira",
      "recolher itens",
      "pegar coisa",
      "coletar material",
      "gather",
      "gather stuff",
      "collect items",
      "pick up wood",
      "collect materials",
      "get resources",
      "grab supplies",
    ],
    responses: [
      "Gathering resources now.",
      "Collecting materials.",
      "Got it, going to gather stuff.",
    ],
  },
  {
    name: "fish",
    trainingPhrases: [
      "pescar",
      "pegar peixe",
      "ir pescar",
      "pesca",
      "jogar vara",
      "vai pro rio",
      "pegar uns peixes",
      "fish",
      "go fishing",
      "catch fish",
      "go fish",
      "throw the rod",
      "fishing time",
    ],
    responses: [
      "Fishing time.",
      "I'll go catch some fish.",
      "Heading to the lake.",
    ],
  },
  {
    name: "smelt",
    trainingPhrases: [
      "fundir",
      "forjar",
      "usar fornalha",
      "esquentar minério",
      "derreter ferro",
      "usar forno",
      "refinar minério",
      "smelt",
      "forge",
      "heat ore",
      "use furnace",
      "smelt ores",
      "make ingots",
      "melt iron",
    ],
    responses: [
      "Smelting the ores now.",
      "Using the furnace.",
      "Turning ores into ingots.",
    ],
  },
  {
    name: "alchemy",
    trainingPhrases: [
      "fazer poção",
      "usar alquimia",
      "criar poções",
      "preparar poção",
      "usar bancada de poções",
      "brew",
      "brew potions",
      "make potions",
      "use brewing stand",
      "mix potions",
    ],
    responses: [
      "Mixing potions now.",
      "Time for alchemy.",
      "Brewing something special.",
    ],
  },
  {
    name: "raid",
    trainingPhrases: [
      "raid",
      "lutar",
      "combater",
      "ataque",
      "defender vila",
      "defender aldeia",
      "enfrentar inimigos",
      "fight",
      "raid attack",
      "defend village",
      "battle",
      "defend us",
      "fight mobs",
      "fight enemies",
    ],
    responses: [
      "Defending the village!",
      "Let's fight!",
      "We're under attack!",
    ],
  },
  {
    name: "explore",
    trainingPhrases: [
      "explorar",
      "explora",
      "achar estrutura",
      "encontrar tesouro",
      "andar por aí",
      "viajar",
      "ver o mapa",
      "explore",
      "go exploring",
      "find treasure",
      "discover",
      "explore map",
      "check around",
      "adventure",
    ],
    responses: [
      "Let's explore.",
      "Going on an adventure.",
      "Exploration time!",
    ],
  },
  {
    name: "craft",
    trainingPhrases: [
      "criar",
      "fabricar",
      "fazer item",
      "usar bancada",
      "criar ferramenta",
      "montar item",
      "craftar",
      "craft",
      "craft items",
      "make tools",
      "use crafting table",
      "make something",
      "craft weapons",
    ],
    responses: ["Crafting now.", "Making items.", "Using the crafting table."],
  },
];
